---
title: "Gov 50 Final Project: GDP Growth and Democratization in Kyrgyzstan"
author: "Roxana Joyce Chen"
description: "Does GDP growth facilitate democratization? In this study, I plan to examine the extent to which GDP growth begets democratic progress. I hypothesize that GDP growth allows democratic progress to occur through factors such as increased governmental capacity, heightened foreign investment, strengthened economic and political institutions, and a more stable middle class."
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does GDP growth facilitate democratization?  In this study, I plan to examine the extent to which GDP growth begets democratic progress. I hypothesize that GDP growth allows democratic progress to occur through factors such as increased governmental capacity, heightened foreign investment, strengthened economic and political institutions, and a more stable middle class. My explanatory variable of interest is the Kyrgyz GDP growth rate from its founding in 1991 to present, according to World Bank data. My outcome variable is the state of liberal democracy in Kyrgyzstan in each associated year, given by VDem data capturing Kyrgyzstan’s annual Liberal Democracy Index (LDI). The LDI is measured one a scale from 0 to 1, and is an aggregate rating of a country’s electoral democracy levels, civil liberty protections, degrees of legal and judicial independence, and governance accountability mechanisms. If I observe greater scores on the LDI in periods of Kyrgyz economic growth, this would support my hypothesis that GDP growth is positively associated with democratic progress; on the other hand, if LDI scores were to drop during periods of economic growth, this evidence would contradict my hypothesis. When I ultimately run my regression, I would need a positive, statistically significant coefficient to corroborate my hypothesis.


```{r}
library(tidyverse)
library(broom)
library(ggplot2)
library(modelr)

```

